### ISSUE TITLE
Make the size of a grid row smaller and aligning buttons horizontally?

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/web-design-2-independent-project#1]
Hi @hellachella and @jessjodoin, 

I having two issues that I'm currently trying to resolve on my website at the desktop screen size (media query: 60em).

Firstly, on the homepage I'm using grids to format the content and I want to make the grid row that contains the <h2>SPEAKERS</h2> smaller so there's not such a gap between the h2 and the images below on the following row? Any ideas about how I would be able to do that?

Also, on the Tickets page I want to have the "select" buttons align horizontally, but I'm having some issues with that as well. In the mobile version, I used position relative and absolute to align them within their respective cards but was having formatting issues when I tried to re-align them at the larger screen size so I switched them to display:block to begin formatting. Not sure if I should still be using position absolute and relative to align them or if there's a way to horizontally align them with display: block?

Thanks in advance!

**Comment by JessJodoin** [comment]
For the issue with the 'speakers' h2 with the grid, the reason why there's so much space is because you wrote that you wanted two rows each taking up 1 fraction of the available space so each row takes up the same amount of space. 

To stop that we need to let the browser make up the rest of the grid (the implicit grid thing) by removing one of the 1fr units from the `grid-template-rows` under .speakers in your css

**Comment by JessJodoin** [comment]
For the ticket cards, you could try making each of the card surrounding `<div>`s a flex container with `display: flex;` and `justify-content: space-between;` (similar to the modularity-mindfulness assignment from week 3)

Also add `flex-direction: column;` to make the elements inside stack 😄
