### ISSUE TITLE
Parse issue on final line of CSS?

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/web-design-2-independent-project#4]
Hi @hellachella and @jessjodoin,

I'm running my code through Markbot as I go and I've continually got an error message for the last curly bracket on line 593 of my CSS (the very last line). I've tried add/removing an extra space and indenting and I'm still getting an error message. Any ideas as to what could resolve this?

Thanks!

**Comment by JessJodoin** [comment]
I think the reason you're getting that Markbot issue is because your first media query (line 325) isn't closed. So add a closing brace at line 344. 

Also all of the css inside the media queries isn't indented far enough, so once you close the first media query, command A all your css and go to edit > lines > auto indent and that will fix the indentation 😄
